### PR TITLE
Add reasons for writing readmes

### PR DESCRIPTION
**Pull request by ncanning**
I'm helping

### CODE REVIEW

**Comment by thisguycodes** [comment]
What problem does this change solve? Can you justify the added complexity here?

**Comment by ncanning** [comment]
?

**Comment by ncanning** [comment]
Look dude I'm just trying to contribute to open source so my contribution graph will look more impressive

**Comment by thisguycodes** [comment]
I'll take a look if I find the time

**Comment by ajvondrak** [comment]
:+1:

**Pull request merged**
